### ISSUE TITLE
Need any more help?

### ISSUE THREAD

**Issue by dguo** [jwilm/alacritty.io#1]
Hello,

I was just wondering if you could use any more help on making this website. I saw from the related issue in the main repo that you already have a few people helping out, so if it's a case of too many cooks in the kitchen, I totally understand.

I'm not a design expert by any means, but I've been working on some small, static websites on the side, so I think I'd be able to help out.

**Comment by asilvadesigns** [comment]
Hi @dguo, thanks for the offer! I'll be pushing up a Jekyll boilerplate pretty soon here, actually began work on it yesterday haha, just a few hours before your issue came in.

So I think we're cool on the dev side, immediately anyways, but with regard to design... there was a mockup posted by @net on the main alacritty repo here: https://github.com/jwilm/alacritty/issues/285 , which is a neat idea, minimalistic, and @jwilm liked it, so I'll be referencing that.

But it'd be sweet to get some other ideas, that's not really an area that has been explored yet. I have a few ideas, I'm sure @EdenSG does as well. I think we've all been a bit busy recently : ).

**Comment by dguo** [comment]
Sounds good. That mockup does look great! I'll close this out then.

Just a suggestion: instead of using GitHub Pages to host it, I recommend checking out [Netlify](https://www.netlify.com/). The free tier should be good enough, and it has some pretty nice features, like SSL support for custom domains (instead of having to put Cloudflare in front of GitHub Pages).
